### ISSUE TITLE
Defect Fixing: Cash Field Value not cleared after sign-out

### ISSUE THREAD

**Issue by nivritii** [Raghuramgrr/vmc#1]
Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the Maintainer successfully pushed “Press Here When Finished”. The simulation does not clear the values on the completion of Maintenance Session. Upon subsequent login, the cash previously held and collected persists in display.

Assigning to Technical Lead for bug fixing

**Comment by cherrygu1209** [comment]
As the TL, assigning to developer-cherrygu1209 to do the bug fix and analyst @kirubah  to do the necessary changes to the Design Model Report.

**Comment by cherrygu1209** [comment]
As a developer, I have uploaded the file MaintenanceController.java which contains fixed codes. 
Reassigning to TL.

**Comment by cherrygu1209** [comment]
TL assigning to QA for testing @kirubah

**Comment by kirubah** [comment]
With the bug fix, the data in cash filed resets after session.
Hence verified bug fix and passed. 
Reassigning to TL after completion of verification @cherrygu1209.

**Comment by cherrygu1209** [comment]
As a TL, the bug fix has been completed, and then will assign to the PM for closing. @nivritii

**Comment by nivritii** [comment]
Closing Issue. Assigning CM @Raghuramgrr  to tag and release as 1.0.8.1.

**Comment by Raghuramgrr** [comment]
Defect fixed 
Released as tag **1.0.8.1**
