### ISSUE TITLE
Enhancement:  Display Denomination Quantity and Amount Expected to Collected

### ISSUE THREAD

**Issue by nivritii** [Raghuramgrr/vmc#3]
Denomination Quantity and Amount that totals to Cash Held and Coins Expected to Collected to be displayed.
Login to VCMS
Total cash collected and the total number of coins by denomination should be displayed in Maintenance Panel screen.

Assigning to TL @cherrygu1209 to work on the enhancement.

**Comment by cherrygu1209** [comment]
As a TL, this enhancement is assigned to the developer @Yuejun-PatrickLi and for design model report, it will be assigned to the analyst @kirubah

**Comment by Yuejun-PatrickLi** [comment]
Enhancement has been completed, assigning to @cherrygu1209  TL

**Comment by cherrygu1209** [comment]
As a TL, the enhancement improvement will be assigned to the QA @kirubah

**Comment by kirubah** [comment]
VMCS Enhancement - Verified Test Status
1.A new Amount column needs to be added next to Quantity Column - ( Pass )
2.With the Show Total Cash Held button along with Quantity of Coins, a new field to display Amount of coins to be added - ( Pass )
3.On click of Show Total Cash Held button both Quantity and Amount to be displayed in the respective fields - ( Pass )
4.On click of Press To Collect All Cash button Collect cash field should be displayed with respective value based on the Amount and Quantity field - ( Pass )

Assigning to TL @cherrygu1209  on completion of testing.

**Comment by nivritii** [comment]
As analyst, have updated the DMR report and added to the enhancement branch.
Assigning to TL @cherrygu1209 for completion of documentation.

**Comment by cherrygu1209** [comment]
As a TL, the enhancement and document have been completed already, and will assign to PM for closing @nivritii

**Comment by nivritii** [comment]
Assigning to CM @Raghuramgrr to tag and release enhancement as 1.0.9.

**Comment by Raghuramgrr** [comment]
Enhancement approved by CM , Fixed and **released** with tag **1.0.9**
